config/routes.rb
Rails.application.routes.draw do
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "clearance/users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"
  get 'bookings', to: "bookings#index", as: 'bookings'

  get 'contact', to: "contact#index", as: 'contact'

  get 'about', to: "about#index", as: 'about'

	root 'home#index', as: 'home'

  resources :bikes
  resources :bookings
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bike.rb
class Bike < ApplicationRecord
  # single type of bike may belong to many bookings 
  has_and_belongs_to_many :bookings
end

app/models/booking.rb
class Booking < ApplicationRecord
  # booking belongs to bike and user.
  belongs_to :bike
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  include Clearance::User
  # single user can have many bookings. 
  has_many :bookings
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
  protect_from_forgery with: :exception
end

app/controllers/bikes_controller.rb
class BikesController < ApplicationController
  before_action :set_bike, only: [:show, :edit, :update, :destroy]

  # GET /bikes
  # GET /bikes.json
  def index
    @bikes = Bike.all
  end

  # GET /bikes/1
  # GET /bikes/1.json
  def show
  end

  # GET /bikes/new
  def new
    @bike = Bike.new
  end

  # GET /bikes/1/edit
  def edit
  end

  # POST /bikes
  # POST /bikes.json
  def create
    @bike = Bike.new(bike_params)

    respond_to do |format|
      if @bike.save
        format.html { redirect_to @bike, notice: 'Bike was successfully created.' }
        format.json { render :show, status: :created, location: @bike }
      else
        format.html { render :new }
        format.json { render json: @bike.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bikes/1
  # PATCH/PUT /bikes/1.json
  def update
    respond_to do |format|
      if @bike.update(bike_params)
        format.html { redirect_to @bike, notice: 'Bike was successfully updated.' }
        format.json { render :show, status: :ok, location: @bike }
      else
        format.html { render :edit }
        format.json { render json: @bike.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bikes/1
  # DELETE /bikes/1.json
  def destroy
    @bike.destroy
    respond_to do |format|
      format.html { redirect_to bikes_url, notice: 'Bike was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bike
      @bike = Bike.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bike_params
      params.require(:bike).permit(:bike_type, :description, :image_url, :cost_per_hour, :day_rate, :weekend_rate, :avail, :qty, :location)
    end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  # to access these routes, one must be logged in.
  before_action :require_login
  
  def index
    # get bookins of the user who is currently logged in.
    @bookings = Booking.all().where(:user_id => current_user.id)
  end

  def create
    # we get form data via POST method. we use Booking.new() to create a new record in the db
    # we don't watch unwanted data to be inserted in the db, we write a private function that lets
    # us permit which data we want to insert data.
    @booking = Booking.new(booking_params)
    if @booking.save

      # we update the quantity and available flag in the db.
      @qty_to_remove = @booking.qty
      @bike_id = @booking.bike_id

      @bike = Bike.find(@bike_id);
      @bike.qty = @bike.qty - @qty_to_remove;
      
      if(@bike.qty == 0)
        @bike.avail = 0
      end

      # update quantity in bike table and also avail flag.
      if @bike.save
        # after we save to db. we send user to /bookings path
        redirect_to bookings_path
      else
        redirect_to home_path
      end
    else
      # if something is wrong. we render home path.
      redirect_to home_path
    end

  end

  def show
    # get booking data by id in the URL.
    @booking = Booking.find(params[:id])

    # we subtract weekend days by number of days selected by user
    @weekdays = @booking.days - @booking.weekenddays
    @weekends = @booking.weekenddays

    # total hours times cost per hour.
    @total_hours_cost = @booking.hours * @booking.bike.cost_per_hour

    # get day and weekend rate of the bike chosen.
    @day_rate = @booking.bike.day_rate
    @weekend_rate = @booking.bike.weekend_rate

    # calculate weekday and weekend price
    @total_days_cost = (@weekdays * @day_rate) + (@weekends * @weekend_rate)


    puts "+++++ " + @total_days_cost.to_s + " " + @total_hours_cost.to_s
    
    # total number of hours bike is rented for times per hour cost.
    @total_cost = @total_days_cost + @total_hours_cost
  end

  private
  def booking_params
    # Allows you to choose which attributes should be whitelisted for mass updating and thus prevent accidentally exposing that which shouldn't be exposed.
    params.require(:booking).permit(:bike_id, :hours, :qty, :start_date, :end_date, :user_id, :days, :weekdays, :weekenddays)
  end
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    # get only those bikes which are available
    @bikes = Bike.all().where(:avail => 1)
    @booking = Booking.new
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bikes_helper.rb
module BikesHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/about/index.html.erb
<div class="container">
  <h1>About</h1>
</div>

app/views/bikes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Bikes</h1>

<table>
  <thead>
    <tr>
      <th>Bike type</th>
      <th>Description</th>
      <th>Image url</th>
      <th>Cost per hour</th>
      <th>Day rate</th>
      <th>Weekend rate</th>
      <th>Avail</th>
      <th>Qty</th>
      <th>Location</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bikes.each do |bike| %>
      <tr>
        <td><%= bike.bike_type %></td>
        <td><%= bike.description %></td>
        <td><%= bike.image_url %></td>
        <td><%= bike.cost_per_hour %></td>
        <td><%= bike.day_rate %></td>
        <td><%= bike.weekend_rate %></td>
        <td><%= bike.avail %></td>
        <td><%= bike.qty %></td>
        <td><%= bike.location %></td>
        <td><%= link_to 'Show', bike %></td>
        <td><%= link_to 'Edit', edit_bike_path(bike) %></td>
        <td><%= link_to 'Destroy', bike, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bike', new_bike_path %>

app/views/bikes/show.html.erb
<p id="notice">
  <%= notice %>
</p>
<div class="container bg-white p-2">
  <div class="row p-5">
    <div class="col">
      <p>
        <strong>Bike type:</strong>
        <%= @bike.bike_type %>
      </p>

      <p>
        <strong>Description:</strong>
        <%= @bike.description %>
      </p>

      <p>
        <strong>Cost per hour:</strong>
        <%= @bike.cost_per_hour %>
      </p>

      <p>
        <strong>Day rate:</strong>
        <%= @bike.day_rate %>
      </p>
    </div>
    <div class="col">
      <p>
        <strong>Weekend rate:</strong>
        <%= @bike.weekend_rate %>
      </p>

      <p>
        <strong>Qty:</strong>
        <%= @bike.qty %>
      </p>

      <p>
        <strong>Location:</strong>
        <%= @bike.location %>
      </p>
    </div>
  </div>

  <%= link_to 'Back', home_path, :class => "text-dark" %>

</div>

app/views/bookings/index.html.erb
<div class="container">
  <% if !@bookings.empty? %>
    <h1 class="text-light my-4">All Bookings</h1>
    <table class="table table-light table-hover text-center">
      <thead class="bg-warning p-5">
        <tr>
          <th scope="col">#</th>
          <th scope="col">Bike</th>
          <th scope="col">Start Date</th>
          <th scope="col">End Date</th>
          <th scope="col">Quantity</th>
          <th scope="col">Number of Days</th>
        </tr>
      </thead>
      <tbody>
        <% @bookings.each_with_index do |booking, index| %>
          <tr onclick="window.location.href='<%= booking_path(booking) %>'">
            <th scope="row">
              <%= index + 1 %>
            </th>
            <td>
              <%= booking.bike.bike_type %>
            </td>
            <td>
              <%= booking.start_date %>
            </td>
            <td>
              <%= booking.end_date %>
            </td>
            <td>
              <%= booking.qty %>
            </td>
            <td>
              <%= booking.days %>
            </td>
          </tr>
          <% end %>
      </tbody>
    </table>
    <% else %>
      <div class="text-light">
        <h2 class="my-4"> Sorry! No bookings available.</h2>
        <p>Click
          <%= link_to "Book Now", home_path, {:class => "text-light"} %> to Book</p>
      </div>
      <% end %>
</div>

app/views/bookings/show.html.erb
<div class="container">
  <div class="row bg-warning rounded p-3 mt-5">
    <h2>Booking Summary:</h2>
  </div>
  <div class="row bg-light p-5 mt-1 rounded">
    <div class="col">
      <%=image_tag(@booking.bike.image_url, { :class => "img-fluid", :alt => "Card Image"})%>
    </div>
    <div class="col">
      <a href="<%= bike_path(@booking.bike) %>" class="a-hover">
        <h2 class="text-muted mb-3">
          <%= @booking.bike.bike_type %>
        </h2>
      </a>
      <hr>
      <div class="row">
        <div class="col">
          <p>
            <span>Quantity:</span>
            <strong>
              <%= @booking.qty %>
            </strong>
          </p>
          <p>
            <span>Booked On:</span>
            <strong>
              <%= @booking.created_at.to_s[0..10] %>
            </strong>
          </p>
          <p>
            <span>Start Date:</span>
            <strong>
              <%= @booking.start_date %>
            </strong>
          </p>
          <p>
            <span>End Date:</span>
            <strong>
              <%= @booking.end_date %>
            </strong>
          </p>
          <p>
            <span>No. of Weekend Days:</span>
            <strong>
              <%= @booking.weekenddays ? @booking.weekenddays : 'nil' %>
            </strong>
          </p>
          <p>
            <span>Total No. of Days:</span>
            <strong>
              <%= @booking.days ? @booking.days : 'nil' %>
            </strong>
          </p>
        </div>
        <div class="col border-left">
          <p>
            <span>No of Hours:</span>
            <strong>
              <%= (@booking.hours).to_s + "hrs" %>
            </strong>
          </p>
        </div>
      </div>
      <hr>
      <p>
        <span class="lead text-muted">Total Cost:</span>
        <strong>
          <%= "$" + @total_cost.to_s%>
        </strong>
      </p>
      <hr>
      <%= link_to "Go back", bookings_path, :class => "text-dark"%>
        <%= link_to "Book More", home_path, :class => "text-dark"%>
    </div>
  </div>
</div>

app/views/contact/index.html.erb
<div class="container">
  <h1>Contact</h1>
</div>

app/views/home/_carousel.html.erb
<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel" data-interval="3000">
  <ol class="carousel-indicators">
    <% Bike.all.each_with_index do |bike, index| %>
      <li data-target="#carouselExampleIndicators" data-slide-to="<%=index%>" class="<%= index == 0 ? " active ": " "%>"></li>
      <% end %>
  </ol>
  <div class="carousel-inner">
    <% Bike.all.each_with_index do |bike, index| %>
      <div class="carousel-item <%= index == 0 ? " active " : '' %>">
        <%=image_tag(bike.image_url, { :class => "img-fluid w-100", :alt => "Card Image"})%>
          <div class="carousel-caption text-white d-none d-md-block">
            <h3 class="display-4">
              <%= bike.bike_type %>
            </h3>
            <p>
              <%= bike.description %>
            </p>
          </div>
      </div>
      <% end %>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

app/views/home/_showcase.html.erb
<div class="bg-light p-5">
  <h1 class="display-3">Various Bikes Available</h1>
  <hr>
  <div class="row">
    <% Bike.all.each do |bike| %>
      <a href="<%= bike_path(bike)%>" class="col-md-6">
        <div class="card text-white showcase">
          <%=image_tag(bike.image_url, { :class => "img-fluid w-100 " + bike.bike_type, :alt => "Card Image"})%>
            <div class="card-img-overlay">
              <h2 class="card-title">
                <%=bike.bike_type%>
              </h2>
              <p class="card-text">
                <%=bike.description%>
              </p>
              <p class="card-text">
                <%= "$" + bike.cost_per_hour.to_s %> per hour /
                  <%= "$" + bike.day_rate.to_s %> per day /
                    <%= "$" + bike.weekend_rate.to_s %> per weekend day
              </p>
              <p class="card-text">
                Location:
                <%= bike.location%>
              </p>
            </div>
        </div>
      </a>
      <% end %>
  </div>
</div>

app/views/home/index.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <header class="home-page">
        <div class="text-white form-holder p-4 my-4">
          <h2 class="mb-3 font-weight-normal"> Rent A Bike Now </h2>
          <%= form_for(@booking) do |f| %>
            <div class="form-group">
              <label for="bike-type">Bike Type</label>
              <%= f.select(:bike_id , @bikes.all.collect {|p| [ p.bike_type, p.id ]}, {},
                    :class => "form-control bikes-select",
                    :onchange => "changeQuantity(event)") %>
            </div>
            <div class="form-group">
              <label for="quantity">Quantity</label>
              <%= f.number_field :qty, { :class => "form-control",:id => "quantity", :min => 1} %>
                <small>Available:
                  <span id="available">0</span>
                </small>
            </div>
            <div class="form-group">
              <label for="start-date">Start Date</label>
              <%= f.datetime_local_field :start_date, { :class => "form-control",:id => "start-date", :min => 1, :onchange => "changeEndDate(event)" } %>
            </div>
            <div class="form-group">
              <label for="end-date">End Date</label>
              <%= f.datetime_local_field :end_date, { :class => "form-control",:id => "end-date", :min => 1, :onchange => "noOfDays()" } %>
            </div>
            <small>Number Of Days:
              <span id="no-of-days">1</span>
            </small>
            <br>
            <%= f.hidden_field :user_id, value: current_user ? current_user.id: 'nill' %>
              <%= f.hidden_field :days, {:value => 1, :id => "no_of_days"} %>
                <%= f.hidden_field :weekdays, {:value => 0, :id => "weekdays"} %>
                  <%= f.hidden_field :weekenddays, {:value => 0, :id => "weekenddays"} %>
                    <%= f.hidden_field :hours, {:value => 0, :id => "no_of_hours"} %>
                      <%= f.submit :submit, :class => "btn btn-outline-light mt-2" %>
                        <% end %>
        </div>
      </header>
    </div>
    <div class="col">
      <%= render partial: 'carousel' %>
    </div>
  </div>
</div>
<%= render partial: 'showcase' %>

  <script>
    changeQuantity(null, document.querySelector(".bikes-select option:nth-child(1)").value);
    changeStartDate();
    changeEndDate();
    checkNoOfDays();
    checkNoofHours();
  </script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>RentABike</title>
  <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css' %>
      <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
        <%= javascript_include_tag 'jq.js' %>
          <%= javascript_include_tag 'bs.js' %>
            <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <div class="navbar-custom fixed-top d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 border-bottom shadow-sm">
    <h3 class="my-0 mr-md-auto font-weight-bold">Rent A Bike</h3>
    <nav class="my-2 my-md-0 mr-md-3">
      <%= link_to("Home", home_path, {:class => "p-2 text-light"}) %>
        <% if signed_in? %>
          <%= link_to 'Bookings', bookings_path, :class => "p-2 text-light" %>
            <%= link_to 'Sign out', sign_out_path, method: :delete, :class => "p-2 text-light" %>
              <% else %>
                <%= link_to 'Sign in', sign_in_path, :class => "p-2 text-light"%>
                  <%= link_to 'Sign up', sign_up_path, :class => "p-2 text-light"%>
                    <% end %>

    </nav>
  </div>
  <div class="adjustment"></div>
  <%= yield %>
    </div>
</body>

</html>

app/views/users/_form.html.erb
<div class="form-group">
  <%= form.label :email %>
    <%= form.text_field :email, type: 'email', :class => "form-control" %>
</div>

<div class="form-group">
  <%= form.label :password %>
    <%= form.password_field :password, :class => "form-control" %>
</div>

app/views/users/new.html.erb
<div class="container">
  <div id="clearance" class="sign-up">
    <h2>
      <%= t(".title") %>
    </h2>

    <%= form_for @user do |form| %>
      <%= render partial: '/users/form', object: form %>

        <div class="submit-field">
          <%= form.submit :class => "btn btn-outline-light" %>
        </div>

        <div class="other-links mt-3">
          <%= link_to t(".sign_in"), sign_in_path, {:class => "text-white pl-1"}%>
        </div>
        <% end %>
  </div>
</div>